// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEohl_hhVYLD3ENSKThyBPtH1WKL2_f94',
    appId: '1:895249592534:web:2e21f8bbd268989ed19977',
    messagingSenderId: '895249592534',
    projectId: 'fyp-project-74085',
    authDomain: 'fyp-project-74085.firebaseapp.com',
    databaseURL: 'https://fyp-project-74085-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-project-74085.firebasestorage.app',
    measurementId: 'G-VV5MCFNWR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DN7FBCvDaGs1wMQUsgVGbYhGSjlQv24',
    appId: '1:895249592534:android:67d784b43981ce6ed19977',
    messagingSenderId: '895249592534',
    projectId: 'fyp-project-74085',
    databaseURL: 'https://fyp-project-74085-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-project-74085.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEohl_hhVYLD3ENSKThyBPtH1WKL2_f94',
    appId: '1:895249592534:web:493f08809caf8cbed19977',
    messagingSenderId: '895249592534',
    projectId: 'fyp-project-74085',
    authDomain: 'fyp-project-74085.firebaseapp.com',
    databaseURL: 'https://fyp-project-74085-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-project-74085.firebasestorage.app',
    measurementId: 'G-3K5YDQM53L',
  );
}
